import React from 'react';
import LegalPageLayout from '@/components/LegalPageLayout';

const Terms = () => {
  return (
    <LegalPageLayout title="Terms of Use" lastUpdated="June 27, 2025">
      <p>
        These Terms of Use (&quot;Terms&quot;) govern your access to and use of Wanderwise AI
        (&quot;Wanderwise,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), including our
        website, AI-generated travel itineraries, and Instagram messaging integration. By using our
        Service, you agree to these Terms. If you do not agree, please do not use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        Wanderwise is an AI-powered travel planning tool that generates personalized trip
        itineraries based on information you provide, such as destination, trip duration, and travel
        dates. Itineraries are created using artificial intelligence and are intended for
        informational and planning purposes only.
      </p>
      <p>
        We do not book flights, hotels, activities, or other travel services. We are not a travel
        agency, tour operator, or booking platform.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 13 years old to use the Service. If you are under 18, you may use the
        Service only with the involvement and consent of a parent or guardian.
      </p>

      <h2>3. No User Accounts</h2>
      <p>
        Wanderwise does not require registration or login. When you submit a trip request on the
        web, we may assign an anonymous session identifier. When you interact via Instagram, we
        receive your Instagram user ID as provided by Meta.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or in violation of applicable laws</li>
        <li>Submit false, misleading, or harmful information</li>
        <li>Attempt to interfere with, disrupt, or reverse-engineer the Service or its APIs</li>
        <li>Scrape, crawl, or automate access to the Service without our written permission</li>
        <li>Use the Service to generate spam, abusive content, or content that infringes others&apos; rights</li>
        <li>Circumvent rate limits, security measures, or access controls</li>
      </ul>

      <h2>5. AI-Generated Content Disclaimer</h2>
      <p>
        Itineraries are generated by AI and may contain errors, outdated information, or
        recommendations that are not suitable for your circumstances. You are solely responsible
        for verifying all travel details — including visa requirements, safety advisories, opening
        hours, prices, and local regulations — before making any travel decisions.
      </p>
      <p>
        Wanderwise does not guarantee the accuracy, completeness, or suitability of any generated
        content. Use itineraries at your own risk.
      </p>

      <h2>6. Public Trip Pages</h2>
      <p>
        Trips you create may be published on publicly accessible pages with a unique URL. If you
        provide an optional name or Instagram handle, that information may appear on the public trip
        page. Do not submit information you do not want displayed publicly.
      </p>

      <h2>7. Instagram Integration</h2>
      <p>
        If you interact with Wanderwise through Instagram Direct Messages, your use is also subject
        to Meta&apos;s Terms of Service and Privacy Policy. We use Instagram messaging solely to
        facilitate trip planning and deliver itinerary links.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        The Wanderwise name, logo, website design, and underlying software are owned by us or our
        licensors. You may share links to your generated itineraries, but you may not copy,
        reproduce, or commercially exploit the Service or its content without our permission.
      </p>
      <p>
        You retain ownership of the information you submit. By using the Service, you grant us a
        non-exclusive license to use that information to generate, store, and display your itinerary
        as described in our Privacy Policy and Data Storage &amp; Use policy.
      </p>

      <h2>9. Third-Party Services</h2>
      <p>
        The Service relies on third-party providers including OpenAI, MongoDB, Upstash Redis,
        Unsplash, OpenStreetMap Nominatim, Meta (Instagram), and Google AdSense. Your use of those
        services may be subject to their respective terms and policies. We are not responsible for
        third-party websites or services linked from itineraries.
      </p>

      <h2>10. Advertising</h2>
      <p>
        We may display advertisements on certain pages through Google AdSense. Ad content is
        provided by third parties and is not endorsed by Wanderwise.
      </p>

      <h2>11. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF
        ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2>12. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WANDERWISE AND ITS OPERATORS SHALL NOT BE LIABLE FOR
        ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
        PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE OR RELIANCE ON
        AI-GENERATED ITINERARIES — INCLUDING TRAVEL DISRUPTIONS, FINANCIAL LOSSES, OR PERSONAL
        INJURY.
      </p>

      <h2>13. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Wanderwise from any claims, damages, or expenses
        arising from your use of the Service or violation of these Terms.
      </p>

      <h2>14. Termination</h2>
      <p>
        We may suspend or discontinue the Service, or restrict access, at any time without notice.
        You may stop using the Service at any time. Sections that by their nature should survive
        termination (including disclaimers, limitations of liability, and indemnification) will
        remain in effect.
      </p>

      <h2>15. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the Service after changes are
        posted constitutes acceptance of the updated Terms. The &quot;Last updated&quot; date at the
        top of this page indicates when the Terms were last revised.
      </p>

      <h2>16. Governing Law</h2>
      <p>
        These Terms are governed by the laws of India, without regard to conflict-of-law principles.
        Any disputes shall be subject to the exclusive jurisdiction of the courts in Delhi, India.
      </p>

      <h2>17. Contact Us</h2>
      <p>If you have questions about these Terms, contact us at:</p>
      <ul>
        <li>
          Email:{' '}
          <a href="mailto:abhinavmehtadeveloper@gmail.com">abhinavmehtadeveloper@gmail.com</a>
        </li>
      </ul>
    </LegalPageLayout>
  );
};

export default Terms;
